// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Qot_GetOptionChain.proto

#ifndef PROTOBUF_Qot_5fGetOptionChain_2eproto__INCLUDED
#define PROTOBUF_Qot_5fGetOptionChain_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "Common.pb.h"
#include "Qot_Common.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_Qot_5fGetOptionChain_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[6];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsC2SImpl();
void InitDefaultsC2S();
void InitDefaultsOptionItemImpl();
void InitDefaultsOptionItem();
void InitDefaultsOptionChainImpl();
void InitDefaultsOptionChain();
void InitDefaultsS2CImpl();
void InitDefaultsS2C();
void InitDefaultsRequestImpl();
void InitDefaultsRequest();
void InitDefaultsResponseImpl();
void InitDefaultsResponse();
inline void InitDefaults() {
  InitDefaultsC2S();
  InitDefaultsOptionItem();
  InitDefaultsOptionChain();
  InitDefaultsS2C();
  InitDefaultsRequest();
  InitDefaultsResponse();
}
}  // namespace protobuf_Qot_5fGetOptionChain_2eproto
namespace Qot_GetOptionChain {
class C2S;
class C2SDefaultTypeInternal;
extern C2SDefaultTypeInternal _C2S_default_instance_;
class OptionChain;
class OptionChainDefaultTypeInternal;
extern OptionChainDefaultTypeInternal _OptionChain_default_instance_;
class OptionItem;
class OptionItemDefaultTypeInternal;
extern OptionItemDefaultTypeInternal _OptionItem_default_instance_;
class Request;
class RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
class Response;
class ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
class S2C;
class S2CDefaultTypeInternal;
extern S2CDefaultTypeInternal _S2C_default_instance_;
}  // namespace Qot_GetOptionChain
namespace Qot_GetOptionChain {

enum OptionCondType {
  OptionCondType_Unknow = 0,
  OptionCondType_WithIn = 1,
  OptionCondType_Outside = 2
};
bool OptionCondType_IsValid(int value);
const OptionCondType OptionCondType_MIN = OptionCondType_Unknow;
const OptionCondType OptionCondType_MAX = OptionCondType_Outside;
const int OptionCondType_ARRAYSIZE = OptionCondType_MAX + 1;

const ::google::protobuf::EnumDescriptor* OptionCondType_descriptor();
inline const ::std::string& OptionCondType_Name(OptionCondType value) {
  return ::google::protobuf::internal::NameOfEnum(
    OptionCondType_descriptor(), value);
}
inline bool OptionCondType_Parse(
    const ::std::string& name, OptionCondType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<OptionCondType>(
    OptionCondType_descriptor(), name, value);
}
// ===================================================================

class C2S : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Qot_GetOptionChain.C2S) */ {
 public:
  C2S();
  virtual ~C2S();

  C2S(const C2S& from);

  inline C2S& operator=(const C2S& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  C2S(C2S&& from) noexcept
    : C2S() {
    *this = ::std::move(from);
  }

  inline C2S& operator=(C2S&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const C2S& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const C2S* internal_default_instance() {
    return reinterpret_cast<const C2S*>(
               &_C2S_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(C2S* other);
  friend void swap(C2S& a, C2S& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline C2S* New() const PROTOBUF_FINAL { return New(NULL); }

  C2S* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const C2S& from);
  void MergeFrom(const C2S& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(C2S* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string beginTime = 4;
  bool has_begintime() const;
  void clear_begintime();
  static const int kBeginTimeFieldNumber = 4;
  const ::std::string& begintime() const;
  void set_begintime(const ::std::string& value);
  #if LANG_CXX11
  void set_begintime(::std::string&& value);
  #endif
  void set_begintime(const char* value);
  void set_begintime(const char* value, size_t size);
  ::std::string* mutable_begintime();
  ::std::string* release_begintime();
  void set_allocated_begintime(::std::string* begintime);

  // required string endTime = 5;
  bool has_endtime() const;
  void clear_endtime();
  static const int kEndTimeFieldNumber = 5;
  const ::std::string& endtime() const;
  void set_endtime(const ::std::string& value);
  #if LANG_CXX11
  void set_endtime(::std::string&& value);
  #endif
  void set_endtime(const char* value);
  void set_endtime(const char* value, size_t size);
  ::std::string* mutable_endtime();
  ::std::string* release_endtime();
  void set_allocated_endtime(::std::string* endtime);

  // required .Qot_Common.Security owner = 1;
  bool has_owner() const;
  void clear_owner();
  static const int kOwnerFieldNumber = 1;
  const ::Qot_Common::Security& owner() const;
  ::Qot_Common::Security* release_owner();
  ::Qot_Common::Security* mutable_owner();
  void set_allocated_owner(::Qot_Common::Security* owner);

  // optional int32 type = 2;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // optional int32 condition = 3;
  bool has_condition() const;
  void clear_condition();
  static const int kConditionFieldNumber = 3;
  ::google::protobuf::int32 condition() const;
  void set_condition(::google::protobuf::int32 value);

  // optional int32 indexOptionType = 6;
  bool has_indexoptiontype() const;
  void clear_indexoptiontype();
  static const int kIndexOptionTypeFieldNumber = 6;
  ::google::protobuf::int32 indexoptiontype() const;
  void set_indexoptiontype(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Qot_GetOptionChain.C2S)
 private:
  void set_has_owner();
  void clear_has_owner();
  void set_has_indexoptiontype();
  void clear_has_indexoptiontype();
  void set_has_type();
  void clear_has_type();
  void set_has_condition();
  void clear_has_condition();
  void set_has_begintime();
  void clear_has_begintime();
  void set_has_endtime();
  void clear_has_endtime();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr begintime_;
  ::google::protobuf::internal::ArenaStringPtr endtime_;
  ::Qot_Common::Security* owner_;
  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 condition_;
  ::google::protobuf::int32 indexoptiontype_;
  friend struct ::protobuf_Qot_5fGetOptionChain_2eproto::TableStruct;
  friend void ::protobuf_Qot_5fGetOptionChain_2eproto::InitDefaultsC2SImpl();
};
// -------------------------------------------------------------------

class OptionItem : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Qot_GetOptionChain.OptionItem) */ {
 public:
  OptionItem();
  virtual ~OptionItem();

  OptionItem(const OptionItem& from);

  inline OptionItem& operator=(const OptionItem& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  OptionItem(OptionItem&& from) noexcept
    : OptionItem() {
    *this = ::std::move(from);
  }

  inline OptionItem& operator=(OptionItem&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OptionItem& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OptionItem* internal_default_instance() {
    return reinterpret_cast<const OptionItem*>(
               &_OptionItem_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(OptionItem* other);
  friend void swap(OptionItem& a, OptionItem& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline OptionItem* New() const PROTOBUF_FINAL { return New(NULL); }

  OptionItem* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const OptionItem& from);
  void MergeFrom(const OptionItem& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(OptionItem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .Qot_Common.SecurityStaticInfo call = 1;
  bool has_call() const;
  void clear_call();
  static const int kCallFieldNumber = 1;
  const ::Qot_Common::SecurityStaticInfo& call() const;
  ::Qot_Common::SecurityStaticInfo* release_call();
  ::Qot_Common::SecurityStaticInfo* mutable_call();
  void set_allocated_call(::Qot_Common::SecurityStaticInfo* call);

  // optional .Qot_Common.SecurityStaticInfo put = 2;
  bool has_put() const;
  void clear_put();
  static const int kPutFieldNumber = 2;
  const ::Qot_Common::SecurityStaticInfo& put() const;
  ::Qot_Common::SecurityStaticInfo* release_put();
  ::Qot_Common::SecurityStaticInfo* mutable_put();
  void set_allocated_put(::Qot_Common::SecurityStaticInfo* put);

  // @@protoc_insertion_point(class_scope:Qot_GetOptionChain.OptionItem)
 private:
  void set_has_call();
  void clear_has_call();
  void set_has_put();
  void clear_has_put();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::Qot_Common::SecurityStaticInfo* call_;
  ::Qot_Common::SecurityStaticInfo* put_;
  friend struct ::protobuf_Qot_5fGetOptionChain_2eproto::TableStruct;
  friend void ::protobuf_Qot_5fGetOptionChain_2eproto::InitDefaultsOptionItemImpl();
};
// -------------------------------------------------------------------

class OptionChain : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Qot_GetOptionChain.OptionChain) */ {
 public:
  OptionChain();
  virtual ~OptionChain();

  OptionChain(const OptionChain& from);

  inline OptionChain& operator=(const OptionChain& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  OptionChain(OptionChain&& from) noexcept
    : OptionChain() {
    *this = ::std::move(from);
  }

  inline OptionChain& operator=(OptionChain&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OptionChain& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OptionChain* internal_default_instance() {
    return reinterpret_cast<const OptionChain*>(
               &_OptionChain_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(OptionChain* other);
  friend void swap(OptionChain& a, OptionChain& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline OptionChain* New() const PROTOBUF_FINAL { return New(NULL); }

  OptionChain* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const OptionChain& from);
  void MergeFrom(const OptionChain& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(OptionChain* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Qot_GetOptionChain.OptionItem option = 2;
  int option_size() const;
  void clear_option();
  static const int kOptionFieldNumber = 2;
  const ::Qot_GetOptionChain::OptionItem& option(int index) const;
  ::Qot_GetOptionChain::OptionItem* mutable_option(int index);
  ::Qot_GetOptionChain::OptionItem* add_option();
  ::google::protobuf::RepeatedPtrField< ::Qot_GetOptionChain::OptionItem >*
      mutable_option();
  const ::google::protobuf::RepeatedPtrField< ::Qot_GetOptionChain::OptionItem >&
      option() const;

  // required string strikeTime = 1;
  bool has_striketime() const;
  void clear_striketime();
  static const int kStrikeTimeFieldNumber = 1;
  const ::std::string& striketime() const;
  void set_striketime(const ::std::string& value);
  #if LANG_CXX11
  void set_striketime(::std::string&& value);
  #endif
  void set_striketime(const char* value);
  void set_striketime(const char* value, size_t size);
  ::std::string* mutable_striketime();
  ::std::string* release_striketime();
  void set_allocated_striketime(::std::string* striketime);

  // optional double strikeTimestamp = 3;
  bool has_striketimestamp() const;
  void clear_striketimestamp();
  static const int kStrikeTimestampFieldNumber = 3;
  double striketimestamp() const;
  void set_striketimestamp(double value);

  // @@protoc_insertion_point(class_scope:Qot_GetOptionChain.OptionChain)
 private:
  void set_has_striketime();
  void clear_has_striketime();
  void set_has_striketimestamp();
  void clear_has_striketimestamp();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Qot_GetOptionChain::OptionItem > option_;
  ::google::protobuf::internal::ArenaStringPtr striketime_;
  double striketimestamp_;
  friend struct ::protobuf_Qot_5fGetOptionChain_2eproto::TableStruct;
  friend void ::protobuf_Qot_5fGetOptionChain_2eproto::InitDefaultsOptionChainImpl();
};
// -------------------------------------------------------------------

class S2C : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Qot_GetOptionChain.S2C) */ {
 public:
  S2C();
  virtual ~S2C();

  S2C(const S2C& from);

  inline S2C& operator=(const S2C& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  S2C(S2C&& from) noexcept
    : S2C() {
    *this = ::std::move(from);
  }

  inline S2C& operator=(S2C&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2C& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const S2C* internal_default_instance() {
    return reinterpret_cast<const S2C*>(
               &_S2C_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(S2C* other);
  friend void swap(S2C& a, S2C& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline S2C* New() const PROTOBUF_FINAL { return New(NULL); }

  S2C* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const S2C& from);
  void MergeFrom(const S2C& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(S2C* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Qot_GetOptionChain.OptionChain optionChain = 1;
  int optionchain_size() const;
  void clear_optionchain();
  static const int kOptionChainFieldNumber = 1;
  const ::Qot_GetOptionChain::OptionChain& optionchain(int index) const;
  ::Qot_GetOptionChain::OptionChain* mutable_optionchain(int index);
  ::Qot_GetOptionChain::OptionChain* add_optionchain();
  ::google::protobuf::RepeatedPtrField< ::Qot_GetOptionChain::OptionChain >*
      mutable_optionchain();
  const ::google::protobuf::RepeatedPtrField< ::Qot_GetOptionChain::OptionChain >&
      optionchain() const;

  // @@protoc_insertion_point(class_scope:Qot_GetOptionChain.S2C)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Qot_GetOptionChain::OptionChain > optionchain_;
  friend struct ::protobuf_Qot_5fGetOptionChain_2eproto::TableStruct;
  friend void ::protobuf_Qot_5fGetOptionChain_2eproto::InitDefaultsS2CImpl();
};
// -------------------------------------------------------------------

class Request : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Qot_GetOptionChain.Request) */ {
 public:
  Request();
  virtual ~Request();

  Request(const Request& from);

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Request(Request&& from) noexcept
    : Request() {
    *this = ::std::move(from);
  }

  inline Request& operator=(Request&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Request* internal_default_instance() {
    return reinterpret_cast<const Request*>(
               &_Request_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(Request* other);
  friend void swap(Request& a, Request& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Request* New() const PROTOBUF_FINAL { return New(NULL); }

  Request* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Request* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .Qot_GetOptionChain.C2S c2s = 1;
  bool has_c2s() const;
  void clear_c2s();
  static const int kC2SFieldNumber = 1;
  const ::Qot_GetOptionChain::C2S& c2s() const;
  ::Qot_GetOptionChain::C2S* release_c2s();
  ::Qot_GetOptionChain::C2S* mutable_c2s();
  void set_allocated_c2s(::Qot_GetOptionChain::C2S* c2s);

  // @@protoc_insertion_point(class_scope:Qot_GetOptionChain.Request)
 private:
  void set_has_c2s();
  void clear_has_c2s();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::Qot_GetOptionChain::C2S* c2s_;
  friend struct ::protobuf_Qot_5fGetOptionChain_2eproto::TableStruct;
  friend void ::protobuf_Qot_5fGetOptionChain_2eproto::InitDefaultsRequestImpl();
};
// -------------------------------------------------------------------

class Response : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Qot_GetOptionChain.Response) */ {
 public:
  Response();
  virtual ~Response();

  Response(const Response& from);

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(Response&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(Response* other);
  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Response* New() const PROTOBUF_FINAL { return New(NULL); }

  Response* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Response* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string retMsg = 2;
  bool has_retmsg() const;
  void clear_retmsg();
  static const int kRetMsgFieldNumber = 2;
  const ::std::string& retmsg() const;
  void set_retmsg(const ::std::string& value);
  #if LANG_CXX11
  void set_retmsg(::std::string&& value);
  #endif
  void set_retmsg(const char* value);
  void set_retmsg(const char* value, size_t size);
  ::std::string* mutable_retmsg();
  ::std::string* release_retmsg();
  void set_allocated_retmsg(::std::string* retmsg);

  // optional .Qot_GetOptionChain.S2C s2c = 4;
  bool has_s2c() const;
  void clear_s2c();
  static const int kS2CFieldNumber = 4;
  const ::Qot_GetOptionChain::S2C& s2c() const;
  ::Qot_GetOptionChain::S2C* release_s2c();
  ::Qot_GetOptionChain::S2C* mutable_s2c();
  void set_allocated_s2c(::Qot_GetOptionChain::S2C* s2c);

  // optional int32 errCode = 3;
  bool has_errcode() const;
  void clear_errcode();
  static const int kErrCodeFieldNumber = 3;
  ::google::protobuf::int32 errcode() const;
  void set_errcode(::google::protobuf::int32 value);

  // required int32 retType = 1 [default = -400];
  bool has_rettype() const;
  void clear_rettype();
  static const int kRetTypeFieldNumber = 1;
  ::google::protobuf::int32 rettype() const;
  void set_rettype(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Qot_GetOptionChain.Response)
 private:
  void set_has_rettype();
  void clear_has_rettype();
  void set_has_retmsg();
  void clear_has_retmsg();
  void set_has_errcode();
  void clear_has_errcode();
  void set_has_s2c();
  void clear_has_s2c();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr retmsg_;
  ::Qot_GetOptionChain::S2C* s2c_;
  ::google::protobuf::int32 errcode_;
  ::google::protobuf::int32 rettype_;
  friend struct ::protobuf_Qot_5fGetOptionChain_2eproto::TableStruct;
  friend void ::protobuf_Qot_5fGetOptionChain_2eproto::InitDefaultsResponseImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// C2S

// required .Qot_Common.Security owner = 1;
inline bool C2S::has_owner() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void C2S::set_has_owner() {
  _has_bits_[0] |= 0x00000004u;
}
inline void C2S::clear_has_owner() {
  _has_bits_[0] &= ~0x00000004u;
}
inline const ::Qot_Common::Security& C2S::owner() const {
  const ::Qot_Common::Security* p = owner_;
  // @@protoc_insertion_point(field_get:Qot_GetOptionChain.C2S.owner)
  return p != NULL ? *p : *reinterpret_cast<const ::Qot_Common::Security*>(
      &::Qot_Common::_Security_default_instance_);
}
inline ::Qot_Common::Security* C2S::release_owner() {
  // @@protoc_insertion_point(field_release:Qot_GetOptionChain.C2S.owner)
  clear_has_owner();
  ::Qot_Common::Security* temp = owner_;
  owner_ = NULL;
  return temp;
}
inline ::Qot_Common::Security* C2S::mutable_owner() {
  set_has_owner();
  if (owner_ == NULL) {
    owner_ = new ::Qot_Common::Security;
  }
  // @@protoc_insertion_point(field_mutable:Qot_GetOptionChain.C2S.owner)
  return owner_;
}
inline void C2S::set_allocated_owner(::Qot_Common::Security* owner) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(owner_);
  }
  if (owner) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      owner = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, owner, submessage_arena);
    }
    set_has_owner();
  } else {
    clear_has_owner();
  }
  owner_ = owner;
  // @@protoc_insertion_point(field_set_allocated:Qot_GetOptionChain.C2S.owner)
}

// optional int32 indexOptionType = 6;
inline bool C2S::has_indexoptiontype() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void C2S::set_has_indexoptiontype() {
  _has_bits_[0] |= 0x00000020u;
}
inline void C2S::clear_has_indexoptiontype() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void C2S::clear_indexoptiontype() {
  indexoptiontype_ = 0;
  clear_has_indexoptiontype();
}
inline ::google::protobuf::int32 C2S::indexoptiontype() const {
  // @@protoc_insertion_point(field_get:Qot_GetOptionChain.C2S.indexOptionType)
  return indexoptiontype_;
}
inline void C2S::set_indexoptiontype(::google::protobuf::int32 value) {
  set_has_indexoptiontype();
  indexoptiontype_ = value;
  // @@protoc_insertion_point(field_set:Qot_GetOptionChain.C2S.indexOptionType)
}

// optional int32 type = 2;
inline bool C2S::has_type() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void C2S::set_has_type() {
  _has_bits_[0] |= 0x00000008u;
}
inline void C2S::clear_has_type() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void C2S::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 C2S::type() const {
  // @@protoc_insertion_point(field_get:Qot_GetOptionChain.C2S.type)
  return type_;
}
inline void C2S::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:Qot_GetOptionChain.C2S.type)
}

// optional int32 condition = 3;
inline bool C2S::has_condition() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void C2S::set_has_condition() {
  _has_bits_[0] |= 0x00000010u;
}
inline void C2S::clear_has_condition() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void C2S::clear_condition() {
  condition_ = 0;
  clear_has_condition();
}
inline ::google::protobuf::int32 C2S::condition() const {
  // @@protoc_insertion_point(field_get:Qot_GetOptionChain.C2S.condition)
  return condition_;
}
inline void C2S::set_condition(::google::protobuf::int32 value) {
  set_has_condition();
  condition_ = value;
  // @@protoc_insertion_point(field_set:Qot_GetOptionChain.C2S.condition)
}

// required string beginTime = 4;
inline bool C2S::has_begintime() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void C2S::set_has_begintime() {
  _has_bits_[0] |= 0x00000001u;
}
inline void C2S::clear_has_begintime() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void C2S::clear_begintime() {
  begintime_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_begintime();
}
inline const ::std::string& C2S::begintime() const {
  // @@protoc_insertion_point(field_get:Qot_GetOptionChain.C2S.beginTime)
  return begintime_.GetNoArena();
}
inline void C2S::set_begintime(const ::std::string& value) {
  set_has_begintime();
  begintime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Qot_GetOptionChain.C2S.beginTime)
}
#if LANG_CXX11
inline void C2S::set_begintime(::std::string&& value) {
  set_has_begintime();
  begintime_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Qot_GetOptionChain.C2S.beginTime)
}
#endif
inline void C2S::set_begintime(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_begintime();
  begintime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Qot_GetOptionChain.C2S.beginTime)
}
inline void C2S::set_begintime(const char* value, size_t size) {
  set_has_begintime();
  begintime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Qot_GetOptionChain.C2S.beginTime)
}
inline ::std::string* C2S::mutable_begintime() {
  set_has_begintime();
  // @@protoc_insertion_point(field_mutable:Qot_GetOptionChain.C2S.beginTime)
  return begintime_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* C2S::release_begintime() {
  // @@protoc_insertion_point(field_release:Qot_GetOptionChain.C2S.beginTime)
  clear_has_begintime();
  return begintime_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void C2S::set_allocated_begintime(::std::string* begintime) {
  if (begintime != NULL) {
    set_has_begintime();
  } else {
    clear_has_begintime();
  }
  begintime_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), begintime);
  // @@protoc_insertion_point(field_set_allocated:Qot_GetOptionChain.C2S.beginTime)
}

// required string endTime = 5;
inline bool C2S::has_endtime() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void C2S::set_has_endtime() {
  _has_bits_[0] |= 0x00000002u;
}
inline void C2S::clear_has_endtime() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void C2S::clear_endtime() {
  endtime_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_endtime();
}
inline const ::std::string& C2S::endtime() const {
  // @@protoc_insertion_point(field_get:Qot_GetOptionChain.C2S.endTime)
  return endtime_.GetNoArena();
}
inline void C2S::set_endtime(const ::std::string& value) {
  set_has_endtime();
  endtime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Qot_GetOptionChain.C2S.endTime)
}
#if LANG_CXX11
inline void C2S::set_endtime(::std::string&& value) {
  set_has_endtime();
  endtime_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Qot_GetOptionChain.C2S.endTime)
}
#endif
inline void C2S::set_endtime(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_endtime();
  endtime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Qot_GetOptionChain.C2S.endTime)
}
inline void C2S::set_endtime(const char* value, size_t size) {
  set_has_endtime();
  endtime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Qot_GetOptionChain.C2S.endTime)
}
inline ::std::string* C2S::mutable_endtime() {
  set_has_endtime();
  // @@protoc_insertion_point(field_mutable:Qot_GetOptionChain.C2S.endTime)
  return endtime_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* C2S::release_endtime() {
  // @@protoc_insertion_point(field_release:Qot_GetOptionChain.C2S.endTime)
  clear_has_endtime();
  return endtime_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void C2S::set_allocated_endtime(::std::string* endtime) {
  if (endtime != NULL) {
    set_has_endtime();
  } else {
    clear_has_endtime();
  }
  endtime_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), endtime);
  // @@protoc_insertion_point(field_set_allocated:Qot_GetOptionChain.C2S.endTime)
}

// -------------------------------------------------------------------

// OptionItem

// optional .Qot_Common.SecurityStaticInfo call = 1;
inline bool OptionItem::has_call() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OptionItem::set_has_call() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OptionItem::clear_has_call() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::Qot_Common::SecurityStaticInfo& OptionItem::call() const {
  const ::Qot_Common::SecurityStaticInfo* p = call_;
  // @@protoc_insertion_point(field_get:Qot_GetOptionChain.OptionItem.call)
  return p != NULL ? *p : *reinterpret_cast<const ::Qot_Common::SecurityStaticInfo*>(
      &::Qot_Common::_SecurityStaticInfo_default_instance_);
}
inline ::Qot_Common::SecurityStaticInfo* OptionItem::release_call() {
  // @@protoc_insertion_point(field_release:Qot_GetOptionChain.OptionItem.call)
  clear_has_call();
  ::Qot_Common::SecurityStaticInfo* temp = call_;
  call_ = NULL;
  return temp;
}
inline ::Qot_Common::SecurityStaticInfo* OptionItem::mutable_call() {
  set_has_call();
  if (call_ == NULL) {
    call_ = new ::Qot_Common::SecurityStaticInfo;
  }
  // @@protoc_insertion_point(field_mutable:Qot_GetOptionChain.OptionItem.call)
  return call_;
}
inline void OptionItem::set_allocated_call(::Qot_Common::SecurityStaticInfo* call) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(call_);
  }
  if (call) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      call = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, call, submessage_arena);
    }
    set_has_call();
  } else {
    clear_has_call();
  }
  call_ = call;
  // @@protoc_insertion_point(field_set_allocated:Qot_GetOptionChain.OptionItem.call)
}

// optional .Qot_Common.SecurityStaticInfo put = 2;
inline bool OptionItem::has_put() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OptionItem::set_has_put() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OptionItem::clear_has_put() {
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::Qot_Common::SecurityStaticInfo& OptionItem::put() const {
  const ::Qot_Common::SecurityStaticInfo* p = put_;
  // @@protoc_insertion_point(field_get:Qot_GetOptionChain.OptionItem.put)
  return p != NULL ? *p : *reinterpret_cast<const ::Qot_Common::SecurityStaticInfo*>(
      &::Qot_Common::_SecurityStaticInfo_default_instance_);
}
inline ::Qot_Common::SecurityStaticInfo* OptionItem::release_put() {
  // @@protoc_insertion_point(field_release:Qot_GetOptionChain.OptionItem.put)
  clear_has_put();
  ::Qot_Common::SecurityStaticInfo* temp = put_;
  put_ = NULL;
  return temp;
}
inline ::Qot_Common::SecurityStaticInfo* OptionItem::mutable_put() {
  set_has_put();
  if (put_ == NULL) {
    put_ = new ::Qot_Common::SecurityStaticInfo;
  }
  // @@protoc_insertion_point(field_mutable:Qot_GetOptionChain.OptionItem.put)
  return put_;
}
inline void OptionItem::set_allocated_put(::Qot_Common::SecurityStaticInfo* put) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(put_);
  }
  if (put) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      put = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, put, submessage_arena);
    }
    set_has_put();
  } else {
    clear_has_put();
  }
  put_ = put;
  // @@protoc_insertion_point(field_set_allocated:Qot_GetOptionChain.OptionItem.put)
}

// -------------------------------------------------------------------

// OptionChain

// required string strikeTime = 1;
inline bool OptionChain::has_striketime() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OptionChain::set_has_striketime() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OptionChain::clear_has_striketime() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OptionChain::clear_striketime() {
  striketime_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_striketime();
}
inline const ::std::string& OptionChain::striketime() const {
  // @@protoc_insertion_point(field_get:Qot_GetOptionChain.OptionChain.strikeTime)
  return striketime_.GetNoArena();
}
inline void OptionChain::set_striketime(const ::std::string& value) {
  set_has_striketime();
  striketime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Qot_GetOptionChain.OptionChain.strikeTime)
}
#if LANG_CXX11
inline void OptionChain::set_striketime(::std::string&& value) {
  set_has_striketime();
  striketime_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Qot_GetOptionChain.OptionChain.strikeTime)
}
#endif
inline void OptionChain::set_striketime(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_striketime();
  striketime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Qot_GetOptionChain.OptionChain.strikeTime)
}
inline void OptionChain::set_striketime(const char* value, size_t size) {
  set_has_striketime();
  striketime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Qot_GetOptionChain.OptionChain.strikeTime)
}
inline ::std::string* OptionChain::mutable_striketime() {
  set_has_striketime();
  // @@protoc_insertion_point(field_mutable:Qot_GetOptionChain.OptionChain.strikeTime)
  return striketime_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OptionChain::release_striketime() {
  // @@protoc_insertion_point(field_release:Qot_GetOptionChain.OptionChain.strikeTime)
  clear_has_striketime();
  return striketime_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OptionChain::set_allocated_striketime(::std::string* striketime) {
  if (striketime != NULL) {
    set_has_striketime();
  } else {
    clear_has_striketime();
  }
  striketime_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), striketime);
  // @@protoc_insertion_point(field_set_allocated:Qot_GetOptionChain.OptionChain.strikeTime)
}

// repeated .Qot_GetOptionChain.OptionItem option = 2;
inline int OptionChain::option_size() const {
  return option_.size();
}
inline void OptionChain::clear_option() {
  option_.Clear();
}
inline const ::Qot_GetOptionChain::OptionItem& OptionChain::option(int index) const {
  // @@protoc_insertion_point(field_get:Qot_GetOptionChain.OptionChain.option)
  return option_.Get(index);
}
inline ::Qot_GetOptionChain::OptionItem* OptionChain::mutable_option(int index) {
  // @@protoc_insertion_point(field_mutable:Qot_GetOptionChain.OptionChain.option)
  return option_.Mutable(index);
}
inline ::Qot_GetOptionChain::OptionItem* OptionChain::add_option() {
  // @@protoc_insertion_point(field_add:Qot_GetOptionChain.OptionChain.option)
  return option_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Qot_GetOptionChain::OptionItem >*
OptionChain::mutable_option() {
  // @@protoc_insertion_point(field_mutable_list:Qot_GetOptionChain.OptionChain.option)
  return &option_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Qot_GetOptionChain::OptionItem >&
OptionChain::option() const {
  // @@protoc_insertion_point(field_list:Qot_GetOptionChain.OptionChain.option)
  return option_;
}

// optional double strikeTimestamp = 3;
inline bool OptionChain::has_striketimestamp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OptionChain::set_has_striketimestamp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OptionChain::clear_has_striketimestamp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OptionChain::clear_striketimestamp() {
  striketimestamp_ = 0;
  clear_has_striketimestamp();
}
inline double OptionChain::striketimestamp() const {
  // @@protoc_insertion_point(field_get:Qot_GetOptionChain.OptionChain.strikeTimestamp)
  return striketimestamp_;
}
inline void OptionChain::set_striketimestamp(double value) {
  set_has_striketimestamp();
  striketimestamp_ = value;
  // @@protoc_insertion_point(field_set:Qot_GetOptionChain.OptionChain.strikeTimestamp)
}

// -------------------------------------------------------------------

// S2C

// repeated .Qot_GetOptionChain.OptionChain optionChain = 1;
inline int S2C::optionchain_size() const {
  return optionchain_.size();
}
inline void S2C::clear_optionchain() {
  optionchain_.Clear();
}
inline const ::Qot_GetOptionChain::OptionChain& S2C::optionchain(int index) const {
  // @@protoc_insertion_point(field_get:Qot_GetOptionChain.S2C.optionChain)
  return optionchain_.Get(index);
}
inline ::Qot_GetOptionChain::OptionChain* S2C::mutable_optionchain(int index) {
  // @@protoc_insertion_point(field_mutable:Qot_GetOptionChain.S2C.optionChain)
  return optionchain_.Mutable(index);
}
inline ::Qot_GetOptionChain::OptionChain* S2C::add_optionchain() {
  // @@protoc_insertion_point(field_add:Qot_GetOptionChain.S2C.optionChain)
  return optionchain_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Qot_GetOptionChain::OptionChain >*
S2C::mutable_optionchain() {
  // @@protoc_insertion_point(field_mutable_list:Qot_GetOptionChain.S2C.optionChain)
  return &optionchain_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Qot_GetOptionChain::OptionChain >&
S2C::optionchain() const {
  // @@protoc_insertion_point(field_list:Qot_GetOptionChain.S2C.optionChain)
  return optionchain_;
}

// -------------------------------------------------------------------

// Request

// required .Qot_GetOptionChain.C2S c2s = 1;
inline bool Request::has_c2s() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request::set_has_c2s() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request::clear_has_c2s() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request::clear_c2s() {
  if (c2s_ != NULL) c2s_->Clear();
  clear_has_c2s();
}
inline const ::Qot_GetOptionChain::C2S& Request::c2s() const {
  const ::Qot_GetOptionChain::C2S* p = c2s_;
  // @@protoc_insertion_point(field_get:Qot_GetOptionChain.Request.c2s)
  return p != NULL ? *p : *reinterpret_cast<const ::Qot_GetOptionChain::C2S*>(
      &::Qot_GetOptionChain::_C2S_default_instance_);
}
inline ::Qot_GetOptionChain::C2S* Request::release_c2s() {
  // @@protoc_insertion_point(field_release:Qot_GetOptionChain.Request.c2s)
  clear_has_c2s();
  ::Qot_GetOptionChain::C2S* temp = c2s_;
  c2s_ = NULL;
  return temp;
}
inline ::Qot_GetOptionChain::C2S* Request::mutable_c2s() {
  set_has_c2s();
  if (c2s_ == NULL) {
    c2s_ = new ::Qot_GetOptionChain::C2S;
  }
  // @@protoc_insertion_point(field_mutable:Qot_GetOptionChain.Request.c2s)
  return c2s_;
}
inline void Request::set_allocated_c2s(::Qot_GetOptionChain::C2S* c2s) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete c2s_;
  }
  if (c2s) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      c2s = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, c2s, submessage_arena);
    }
    set_has_c2s();
  } else {
    clear_has_c2s();
  }
  c2s_ = c2s;
  // @@protoc_insertion_point(field_set_allocated:Qot_GetOptionChain.Request.c2s)
}

// -------------------------------------------------------------------

// Response

// required int32 retType = 1 [default = -400];
inline bool Response::has_rettype() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Response::set_has_rettype() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Response::clear_has_rettype() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Response::clear_rettype() {
  rettype_ = -400;
  clear_has_rettype();
}
inline ::google::protobuf::int32 Response::rettype() const {
  // @@protoc_insertion_point(field_get:Qot_GetOptionChain.Response.retType)
  return rettype_;
}
inline void Response::set_rettype(::google::protobuf::int32 value) {
  set_has_rettype();
  rettype_ = value;
  // @@protoc_insertion_point(field_set:Qot_GetOptionChain.Response.retType)
}

// optional string retMsg = 2;
inline bool Response::has_retmsg() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Response::set_has_retmsg() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Response::clear_has_retmsg() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Response::clear_retmsg() {
  retmsg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_retmsg();
}
inline const ::std::string& Response::retmsg() const {
  // @@protoc_insertion_point(field_get:Qot_GetOptionChain.Response.retMsg)
  return retmsg_.GetNoArena();
}
inline void Response::set_retmsg(const ::std::string& value) {
  set_has_retmsg();
  retmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Qot_GetOptionChain.Response.retMsg)
}
#if LANG_CXX11
inline void Response::set_retmsg(::std::string&& value) {
  set_has_retmsg();
  retmsg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Qot_GetOptionChain.Response.retMsg)
}
#endif
inline void Response::set_retmsg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_retmsg();
  retmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Qot_GetOptionChain.Response.retMsg)
}
inline void Response::set_retmsg(const char* value, size_t size) {
  set_has_retmsg();
  retmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Qot_GetOptionChain.Response.retMsg)
}
inline ::std::string* Response::mutable_retmsg() {
  set_has_retmsg();
  // @@protoc_insertion_point(field_mutable:Qot_GetOptionChain.Response.retMsg)
  return retmsg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Response::release_retmsg() {
  // @@protoc_insertion_point(field_release:Qot_GetOptionChain.Response.retMsg)
  clear_has_retmsg();
  return retmsg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Response::set_allocated_retmsg(::std::string* retmsg) {
  if (retmsg != NULL) {
    set_has_retmsg();
  } else {
    clear_has_retmsg();
  }
  retmsg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), retmsg);
  // @@protoc_insertion_point(field_set_allocated:Qot_GetOptionChain.Response.retMsg)
}

// optional int32 errCode = 3;
inline bool Response::has_errcode() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Response::set_has_errcode() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Response::clear_has_errcode() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Response::clear_errcode() {
  errcode_ = 0;
  clear_has_errcode();
}
inline ::google::protobuf::int32 Response::errcode() const {
  // @@protoc_insertion_point(field_get:Qot_GetOptionChain.Response.errCode)
  return errcode_;
}
inline void Response::set_errcode(::google::protobuf::int32 value) {
  set_has_errcode();
  errcode_ = value;
  // @@protoc_insertion_point(field_set:Qot_GetOptionChain.Response.errCode)
}

// optional .Qot_GetOptionChain.S2C s2c = 4;
inline bool Response::has_s2c() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Response::set_has_s2c() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Response::clear_has_s2c() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Response::clear_s2c() {
  if (s2c_ != NULL) s2c_->Clear();
  clear_has_s2c();
}
inline const ::Qot_GetOptionChain::S2C& Response::s2c() const {
  const ::Qot_GetOptionChain::S2C* p = s2c_;
  // @@protoc_insertion_point(field_get:Qot_GetOptionChain.Response.s2c)
  return p != NULL ? *p : *reinterpret_cast<const ::Qot_GetOptionChain::S2C*>(
      &::Qot_GetOptionChain::_S2C_default_instance_);
}
inline ::Qot_GetOptionChain::S2C* Response::release_s2c() {
  // @@protoc_insertion_point(field_release:Qot_GetOptionChain.Response.s2c)
  clear_has_s2c();
  ::Qot_GetOptionChain::S2C* temp = s2c_;
  s2c_ = NULL;
  return temp;
}
inline ::Qot_GetOptionChain::S2C* Response::mutable_s2c() {
  set_has_s2c();
  if (s2c_ == NULL) {
    s2c_ = new ::Qot_GetOptionChain::S2C;
  }
  // @@protoc_insertion_point(field_mutable:Qot_GetOptionChain.Response.s2c)
  return s2c_;
}
inline void Response::set_allocated_s2c(::Qot_GetOptionChain::S2C* s2c) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete s2c_;
  }
  if (s2c) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      s2c = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, s2c, submessage_arena);
    }
    set_has_s2c();
  } else {
    clear_has_s2c();
  }
  s2c_ = s2c;
  // @@protoc_insertion_point(field_set_allocated:Qot_GetOptionChain.Response.s2c)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Qot_GetOptionChain

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::Qot_GetOptionChain::OptionCondType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Qot_GetOptionChain::OptionCondType>() {
  return ::Qot_GetOptionChain::OptionCondType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Qot_5fGetOptionChain_2eproto__INCLUDED
