// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Qot_RequestHistoryKLQuota.proto

#ifndef PROTOBUF_Qot_5fRequestHistoryKLQuota_2eproto__INCLUDED
#define PROTOBUF_Qot_5fRequestHistoryKLQuota_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Common.pb.h"
#include "Qot_Common.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_Qot_5fRequestHistoryKLQuota_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[5];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsDetailItemImpl();
void InitDefaultsDetailItem();
void InitDefaultsC2SImpl();
void InitDefaultsC2S();
void InitDefaultsS2CImpl();
void InitDefaultsS2C();
void InitDefaultsRequestImpl();
void InitDefaultsRequest();
void InitDefaultsResponseImpl();
void InitDefaultsResponse();
inline void InitDefaults() {
  InitDefaultsDetailItem();
  InitDefaultsC2S();
  InitDefaultsS2C();
  InitDefaultsRequest();
  InitDefaultsResponse();
}
}  // namespace protobuf_Qot_5fRequestHistoryKLQuota_2eproto
namespace Qot_RequestHistoryKLQuota {
class C2S;
class C2SDefaultTypeInternal;
extern C2SDefaultTypeInternal _C2S_default_instance_;
class DetailItem;
class DetailItemDefaultTypeInternal;
extern DetailItemDefaultTypeInternal _DetailItem_default_instance_;
class Request;
class RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
class Response;
class ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
class S2C;
class S2CDefaultTypeInternal;
extern S2CDefaultTypeInternal _S2C_default_instance_;
}  // namespace Qot_RequestHistoryKLQuota
namespace Qot_RequestHistoryKLQuota {

// ===================================================================

class DetailItem : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Qot_RequestHistoryKLQuota.DetailItem) */ {
 public:
  DetailItem();
  virtual ~DetailItem();

  DetailItem(const DetailItem& from);

  inline DetailItem& operator=(const DetailItem& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DetailItem(DetailItem&& from) noexcept
    : DetailItem() {
    *this = ::std::move(from);
  }

  inline DetailItem& operator=(DetailItem&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DetailItem& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DetailItem* internal_default_instance() {
    return reinterpret_cast<const DetailItem*>(
               &_DetailItem_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(DetailItem* other);
  friend void swap(DetailItem& a, DetailItem& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DetailItem* New() const PROTOBUF_FINAL { return New(NULL); }

  DetailItem* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DetailItem& from);
  void MergeFrom(const DetailItem& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DetailItem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string requestTime = 2;
  bool has_requesttime() const;
  void clear_requesttime();
  static const int kRequestTimeFieldNumber = 2;
  const ::std::string& requesttime() const;
  void set_requesttime(const ::std::string& value);
  #if LANG_CXX11
  void set_requesttime(::std::string&& value);
  #endif
  void set_requesttime(const char* value);
  void set_requesttime(const char* value, size_t size);
  ::std::string* mutable_requesttime();
  ::std::string* release_requesttime();
  void set_allocated_requesttime(::std::string* requesttime);

  // required .Qot_Common.Security security = 1;
  bool has_security() const;
  void clear_security();
  static const int kSecurityFieldNumber = 1;
  const ::Qot_Common::Security& security() const;
  ::Qot_Common::Security* release_security();
  ::Qot_Common::Security* mutable_security();
  void set_allocated_security(::Qot_Common::Security* security);

  // optional int64 requestTimeStamp = 3;
  bool has_requesttimestamp() const;
  void clear_requesttimestamp();
  static const int kRequestTimeStampFieldNumber = 3;
  ::google::protobuf::int64 requesttimestamp() const;
  void set_requesttimestamp(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Qot_RequestHistoryKLQuota.DetailItem)
 private:
  void set_has_security();
  void clear_has_security();
  void set_has_requesttime();
  void clear_has_requesttime();
  void set_has_requesttimestamp();
  void clear_has_requesttimestamp();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr requesttime_;
  ::Qot_Common::Security* security_;
  ::google::protobuf::int64 requesttimestamp_;
  friend struct ::protobuf_Qot_5fRequestHistoryKLQuota_2eproto::TableStruct;
  friend void ::protobuf_Qot_5fRequestHistoryKLQuota_2eproto::InitDefaultsDetailItemImpl();
};
// -------------------------------------------------------------------

class C2S : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Qot_RequestHistoryKLQuota.C2S) */ {
 public:
  C2S();
  virtual ~C2S();

  C2S(const C2S& from);

  inline C2S& operator=(const C2S& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  C2S(C2S&& from) noexcept
    : C2S() {
    *this = ::std::move(from);
  }

  inline C2S& operator=(C2S&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const C2S& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const C2S* internal_default_instance() {
    return reinterpret_cast<const C2S*>(
               &_C2S_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(C2S* other);
  friend void swap(C2S& a, C2S& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline C2S* New() const PROTOBUF_FINAL { return New(NULL); }

  C2S* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const C2S& from);
  void MergeFrom(const C2S& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(C2S* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool bGetDetail = 2;
  bool has_bgetdetail() const;
  void clear_bgetdetail();
  static const int kBGetDetailFieldNumber = 2;
  bool bgetdetail() const;
  void set_bgetdetail(bool value);

  // @@protoc_insertion_point(class_scope:Qot_RequestHistoryKLQuota.C2S)
 private:
  void set_has_bgetdetail();
  void clear_has_bgetdetail();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  bool bgetdetail_;
  friend struct ::protobuf_Qot_5fRequestHistoryKLQuota_2eproto::TableStruct;
  friend void ::protobuf_Qot_5fRequestHistoryKLQuota_2eproto::InitDefaultsC2SImpl();
};
// -------------------------------------------------------------------

class S2C : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Qot_RequestHistoryKLQuota.S2C) */ {
 public:
  S2C();
  virtual ~S2C();

  S2C(const S2C& from);

  inline S2C& operator=(const S2C& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  S2C(S2C&& from) noexcept
    : S2C() {
    *this = ::std::move(from);
  }

  inline S2C& operator=(S2C&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2C& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const S2C* internal_default_instance() {
    return reinterpret_cast<const S2C*>(
               &_S2C_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(S2C* other);
  friend void swap(S2C& a, S2C& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline S2C* New() const PROTOBUF_FINAL { return New(NULL); }

  S2C* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const S2C& from);
  void MergeFrom(const S2C& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(S2C* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Qot_RequestHistoryKLQuota.DetailItem detailList = 3;
  int detaillist_size() const;
  void clear_detaillist();
  static const int kDetailListFieldNumber = 3;
  const ::Qot_RequestHistoryKLQuota::DetailItem& detaillist(int index) const;
  ::Qot_RequestHistoryKLQuota::DetailItem* mutable_detaillist(int index);
  ::Qot_RequestHistoryKLQuota::DetailItem* add_detaillist();
  ::google::protobuf::RepeatedPtrField< ::Qot_RequestHistoryKLQuota::DetailItem >*
      mutable_detaillist();
  const ::google::protobuf::RepeatedPtrField< ::Qot_RequestHistoryKLQuota::DetailItem >&
      detaillist() const;

  // required int32 usedQuota = 1;
  bool has_usedquota() const;
  void clear_usedquota();
  static const int kUsedQuotaFieldNumber = 1;
  ::google::protobuf::int32 usedquota() const;
  void set_usedquota(::google::protobuf::int32 value);

  // required int32 remainQuota = 2;
  bool has_remainquota() const;
  void clear_remainquota();
  static const int kRemainQuotaFieldNumber = 2;
  ::google::protobuf::int32 remainquota() const;
  void set_remainquota(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Qot_RequestHistoryKLQuota.S2C)
 private:
  void set_has_usedquota();
  void clear_has_usedquota();
  void set_has_remainquota();
  void clear_has_remainquota();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Qot_RequestHistoryKLQuota::DetailItem > detaillist_;
  ::google::protobuf::int32 usedquota_;
  ::google::protobuf::int32 remainquota_;
  friend struct ::protobuf_Qot_5fRequestHistoryKLQuota_2eproto::TableStruct;
  friend void ::protobuf_Qot_5fRequestHistoryKLQuota_2eproto::InitDefaultsS2CImpl();
};
// -------------------------------------------------------------------

class Request : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Qot_RequestHistoryKLQuota.Request) */ {
 public:
  Request();
  virtual ~Request();

  Request(const Request& from);

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Request(Request&& from) noexcept
    : Request() {
    *this = ::std::move(from);
  }

  inline Request& operator=(Request&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Request* internal_default_instance() {
    return reinterpret_cast<const Request*>(
               &_Request_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(Request* other);
  friend void swap(Request& a, Request& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Request* New() const PROTOBUF_FINAL { return New(NULL); }

  Request* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Request* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .Qot_RequestHistoryKLQuota.C2S c2s = 1;
  bool has_c2s() const;
  void clear_c2s();
  static const int kC2SFieldNumber = 1;
  const ::Qot_RequestHistoryKLQuota::C2S& c2s() const;
  ::Qot_RequestHistoryKLQuota::C2S* release_c2s();
  ::Qot_RequestHistoryKLQuota::C2S* mutable_c2s();
  void set_allocated_c2s(::Qot_RequestHistoryKLQuota::C2S* c2s);

  // @@protoc_insertion_point(class_scope:Qot_RequestHistoryKLQuota.Request)
 private:
  void set_has_c2s();
  void clear_has_c2s();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::Qot_RequestHistoryKLQuota::C2S* c2s_;
  friend struct ::protobuf_Qot_5fRequestHistoryKLQuota_2eproto::TableStruct;
  friend void ::protobuf_Qot_5fRequestHistoryKLQuota_2eproto::InitDefaultsRequestImpl();
};
// -------------------------------------------------------------------

class Response : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Qot_RequestHistoryKLQuota.Response) */ {
 public:
  Response();
  virtual ~Response();

  Response(const Response& from);

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(Response&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(Response* other);
  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Response* New() const PROTOBUF_FINAL { return New(NULL); }

  Response* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Response* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string retMsg = 2;
  bool has_retmsg() const;
  void clear_retmsg();
  static const int kRetMsgFieldNumber = 2;
  const ::std::string& retmsg() const;
  void set_retmsg(const ::std::string& value);
  #if LANG_CXX11
  void set_retmsg(::std::string&& value);
  #endif
  void set_retmsg(const char* value);
  void set_retmsg(const char* value, size_t size);
  ::std::string* mutable_retmsg();
  ::std::string* release_retmsg();
  void set_allocated_retmsg(::std::string* retmsg);

  // optional .Qot_RequestHistoryKLQuota.S2C s2c = 4;
  bool has_s2c() const;
  void clear_s2c();
  static const int kS2CFieldNumber = 4;
  const ::Qot_RequestHistoryKLQuota::S2C& s2c() const;
  ::Qot_RequestHistoryKLQuota::S2C* release_s2c();
  ::Qot_RequestHistoryKLQuota::S2C* mutable_s2c();
  void set_allocated_s2c(::Qot_RequestHistoryKLQuota::S2C* s2c);

  // optional int32 errCode = 3;
  bool has_errcode() const;
  void clear_errcode();
  static const int kErrCodeFieldNumber = 3;
  ::google::protobuf::int32 errcode() const;
  void set_errcode(::google::protobuf::int32 value);

  // required int32 retType = 1 [default = -400];
  bool has_rettype() const;
  void clear_rettype();
  static const int kRetTypeFieldNumber = 1;
  ::google::protobuf::int32 rettype() const;
  void set_rettype(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Qot_RequestHistoryKLQuota.Response)
 private:
  void set_has_rettype();
  void clear_has_rettype();
  void set_has_retmsg();
  void clear_has_retmsg();
  void set_has_errcode();
  void clear_has_errcode();
  void set_has_s2c();
  void clear_has_s2c();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr retmsg_;
  ::Qot_RequestHistoryKLQuota::S2C* s2c_;
  ::google::protobuf::int32 errcode_;
  ::google::protobuf::int32 rettype_;
  friend struct ::protobuf_Qot_5fRequestHistoryKLQuota_2eproto::TableStruct;
  friend void ::protobuf_Qot_5fRequestHistoryKLQuota_2eproto::InitDefaultsResponseImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DetailItem

// required .Qot_Common.Security security = 1;
inline bool DetailItem::has_security() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DetailItem::set_has_security() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DetailItem::clear_has_security() {
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::Qot_Common::Security& DetailItem::security() const {
  const ::Qot_Common::Security* p = security_;
  // @@protoc_insertion_point(field_get:Qot_RequestHistoryKLQuota.DetailItem.security)
  return p != NULL ? *p : *reinterpret_cast<const ::Qot_Common::Security*>(
      &::Qot_Common::_Security_default_instance_);
}
inline ::Qot_Common::Security* DetailItem::release_security() {
  // @@protoc_insertion_point(field_release:Qot_RequestHistoryKLQuota.DetailItem.security)
  clear_has_security();
  ::Qot_Common::Security* temp = security_;
  security_ = NULL;
  return temp;
}
inline ::Qot_Common::Security* DetailItem::mutable_security() {
  set_has_security();
  if (security_ == NULL) {
    security_ = new ::Qot_Common::Security;
  }
  // @@protoc_insertion_point(field_mutable:Qot_RequestHistoryKLQuota.DetailItem.security)
  return security_;
}
inline void DetailItem::set_allocated_security(::Qot_Common::Security* security) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(security_);
  }
  if (security) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      security = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, security, submessage_arena);
    }
    set_has_security();
  } else {
    clear_has_security();
  }
  security_ = security;
  // @@protoc_insertion_point(field_set_allocated:Qot_RequestHistoryKLQuota.DetailItem.security)
}

// required string requestTime = 2;
inline bool DetailItem::has_requesttime() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DetailItem::set_has_requesttime() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DetailItem::clear_has_requesttime() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DetailItem::clear_requesttime() {
  requesttime_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_requesttime();
}
inline const ::std::string& DetailItem::requesttime() const {
  // @@protoc_insertion_point(field_get:Qot_RequestHistoryKLQuota.DetailItem.requestTime)
  return requesttime_.GetNoArena();
}
inline void DetailItem::set_requesttime(const ::std::string& value) {
  set_has_requesttime();
  requesttime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Qot_RequestHistoryKLQuota.DetailItem.requestTime)
}
#if LANG_CXX11
inline void DetailItem::set_requesttime(::std::string&& value) {
  set_has_requesttime();
  requesttime_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Qot_RequestHistoryKLQuota.DetailItem.requestTime)
}
#endif
inline void DetailItem::set_requesttime(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_requesttime();
  requesttime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Qot_RequestHistoryKLQuota.DetailItem.requestTime)
}
inline void DetailItem::set_requesttime(const char* value, size_t size) {
  set_has_requesttime();
  requesttime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Qot_RequestHistoryKLQuota.DetailItem.requestTime)
}
inline ::std::string* DetailItem::mutable_requesttime() {
  set_has_requesttime();
  // @@protoc_insertion_point(field_mutable:Qot_RequestHistoryKLQuota.DetailItem.requestTime)
  return requesttime_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DetailItem::release_requesttime() {
  // @@protoc_insertion_point(field_release:Qot_RequestHistoryKLQuota.DetailItem.requestTime)
  clear_has_requesttime();
  return requesttime_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DetailItem::set_allocated_requesttime(::std::string* requesttime) {
  if (requesttime != NULL) {
    set_has_requesttime();
  } else {
    clear_has_requesttime();
  }
  requesttime_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), requesttime);
  // @@protoc_insertion_point(field_set_allocated:Qot_RequestHistoryKLQuota.DetailItem.requestTime)
}

// optional int64 requestTimeStamp = 3;
inline bool DetailItem::has_requesttimestamp() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DetailItem::set_has_requesttimestamp() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DetailItem::clear_has_requesttimestamp() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DetailItem::clear_requesttimestamp() {
  requesttimestamp_ = GOOGLE_LONGLONG(0);
  clear_has_requesttimestamp();
}
inline ::google::protobuf::int64 DetailItem::requesttimestamp() const {
  // @@protoc_insertion_point(field_get:Qot_RequestHistoryKLQuota.DetailItem.requestTimeStamp)
  return requesttimestamp_;
}
inline void DetailItem::set_requesttimestamp(::google::protobuf::int64 value) {
  set_has_requesttimestamp();
  requesttimestamp_ = value;
  // @@protoc_insertion_point(field_set:Qot_RequestHistoryKLQuota.DetailItem.requestTimeStamp)
}

// -------------------------------------------------------------------

// C2S

// optional bool bGetDetail = 2;
inline bool C2S::has_bgetdetail() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void C2S::set_has_bgetdetail() {
  _has_bits_[0] |= 0x00000001u;
}
inline void C2S::clear_has_bgetdetail() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void C2S::clear_bgetdetail() {
  bgetdetail_ = false;
  clear_has_bgetdetail();
}
inline bool C2S::bgetdetail() const {
  // @@protoc_insertion_point(field_get:Qot_RequestHistoryKLQuota.C2S.bGetDetail)
  return bgetdetail_;
}
inline void C2S::set_bgetdetail(bool value) {
  set_has_bgetdetail();
  bgetdetail_ = value;
  // @@protoc_insertion_point(field_set:Qot_RequestHistoryKLQuota.C2S.bGetDetail)
}

// -------------------------------------------------------------------

// S2C

// required int32 usedQuota = 1;
inline bool S2C::has_usedquota() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2C::set_has_usedquota() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2C::clear_has_usedquota() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2C::clear_usedquota() {
  usedquota_ = 0;
  clear_has_usedquota();
}
inline ::google::protobuf::int32 S2C::usedquota() const {
  // @@protoc_insertion_point(field_get:Qot_RequestHistoryKLQuota.S2C.usedQuota)
  return usedquota_;
}
inline void S2C::set_usedquota(::google::protobuf::int32 value) {
  set_has_usedquota();
  usedquota_ = value;
  // @@protoc_insertion_point(field_set:Qot_RequestHistoryKLQuota.S2C.usedQuota)
}

// required int32 remainQuota = 2;
inline bool S2C::has_remainquota() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void S2C::set_has_remainquota() {
  _has_bits_[0] |= 0x00000002u;
}
inline void S2C::clear_has_remainquota() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void S2C::clear_remainquota() {
  remainquota_ = 0;
  clear_has_remainquota();
}
inline ::google::protobuf::int32 S2C::remainquota() const {
  // @@protoc_insertion_point(field_get:Qot_RequestHistoryKLQuota.S2C.remainQuota)
  return remainquota_;
}
inline void S2C::set_remainquota(::google::protobuf::int32 value) {
  set_has_remainquota();
  remainquota_ = value;
  // @@protoc_insertion_point(field_set:Qot_RequestHistoryKLQuota.S2C.remainQuota)
}

// repeated .Qot_RequestHistoryKLQuota.DetailItem detailList = 3;
inline int S2C::detaillist_size() const {
  return detaillist_.size();
}
inline void S2C::clear_detaillist() {
  detaillist_.Clear();
}
inline const ::Qot_RequestHistoryKLQuota::DetailItem& S2C::detaillist(int index) const {
  // @@protoc_insertion_point(field_get:Qot_RequestHistoryKLQuota.S2C.detailList)
  return detaillist_.Get(index);
}
inline ::Qot_RequestHistoryKLQuota::DetailItem* S2C::mutable_detaillist(int index) {
  // @@protoc_insertion_point(field_mutable:Qot_RequestHistoryKLQuota.S2C.detailList)
  return detaillist_.Mutable(index);
}
inline ::Qot_RequestHistoryKLQuota::DetailItem* S2C::add_detaillist() {
  // @@protoc_insertion_point(field_add:Qot_RequestHistoryKLQuota.S2C.detailList)
  return detaillist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Qot_RequestHistoryKLQuota::DetailItem >*
S2C::mutable_detaillist() {
  // @@protoc_insertion_point(field_mutable_list:Qot_RequestHistoryKLQuota.S2C.detailList)
  return &detaillist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Qot_RequestHistoryKLQuota::DetailItem >&
S2C::detaillist() const {
  // @@protoc_insertion_point(field_list:Qot_RequestHistoryKLQuota.S2C.detailList)
  return detaillist_;
}

// -------------------------------------------------------------------

// Request

// required .Qot_RequestHistoryKLQuota.C2S c2s = 1;
inline bool Request::has_c2s() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request::set_has_c2s() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request::clear_has_c2s() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request::clear_c2s() {
  if (c2s_ != NULL) c2s_->Clear();
  clear_has_c2s();
}
inline const ::Qot_RequestHistoryKLQuota::C2S& Request::c2s() const {
  const ::Qot_RequestHistoryKLQuota::C2S* p = c2s_;
  // @@protoc_insertion_point(field_get:Qot_RequestHistoryKLQuota.Request.c2s)
  return p != NULL ? *p : *reinterpret_cast<const ::Qot_RequestHistoryKLQuota::C2S*>(
      &::Qot_RequestHistoryKLQuota::_C2S_default_instance_);
}
inline ::Qot_RequestHistoryKLQuota::C2S* Request::release_c2s() {
  // @@protoc_insertion_point(field_release:Qot_RequestHistoryKLQuota.Request.c2s)
  clear_has_c2s();
  ::Qot_RequestHistoryKLQuota::C2S* temp = c2s_;
  c2s_ = NULL;
  return temp;
}
inline ::Qot_RequestHistoryKLQuota::C2S* Request::mutable_c2s() {
  set_has_c2s();
  if (c2s_ == NULL) {
    c2s_ = new ::Qot_RequestHistoryKLQuota::C2S;
  }
  // @@protoc_insertion_point(field_mutable:Qot_RequestHistoryKLQuota.Request.c2s)
  return c2s_;
}
inline void Request::set_allocated_c2s(::Qot_RequestHistoryKLQuota::C2S* c2s) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete c2s_;
  }
  if (c2s) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      c2s = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, c2s, submessage_arena);
    }
    set_has_c2s();
  } else {
    clear_has_c2s();
  }
  c2s_ = c2s;
  // @@protoc_insertion_point(field_set_allocated:Qot_RequestHistoryKLQuota.Request.c2s)
}

// -------------------------------------------------------------------

// Response

// required int32 retType = 1 [default = -400];
inline bool Response::has_rettype() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Response::set_has_rettype() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Response::clear_has_rettype() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Response::clear_rettype() {
  rettype_ = -400;
  clear_has_rettype();
}
inline ::google::protobuf::int32 Response::rettype() const {
  // @@protoc_insertion_point(field_get:Qot_RequestHistoryKLQuota.Response.retType)
  return rettype_;
}
inline void Response::set_rettype(::google::protobuf::int32 value) {
  set_has_rettype();
  rettype_ = value;
  // @@protoc_insertion_point(field_set:Qot_RequestHistoryKLQuota.Response.retType)
}

// optional string retMsg = 2;
inline bool Response::has_retmsg() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Response::set_has_retmsg() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Response::clear_has_retmsg() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Response::clear_retmsg() {
  retmsg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_retmsg();
}
inline const ::std::string& Response::retmsg() const {
  // @@protoc_insertion_point(field_get:Qot_RequestHistoryKLQuota.Response.retMsg)
  return retmsg_.GetNoArena();
}
inline void Response::set_retmsg(const ::std::string& value) {
  set_has_retmsg();
  retmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Qot_RequestHistoryKLQuota.Response.retMsg)
}
#if LANG_CXX11
inline void Response::set_retmsg(::std::string&& value) {
  set_has_retmsg();
  retmsg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Qot_RequestHistoryKLQuota.Response.retMsg)
}
#endif
inline void Response::set_retmsg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_retmsg();
  retmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Qot_RequestHistoryKLQuota.Response.retMsg)
}
inline void Response::set_retmsg(const char* value, size_t size) {
  set_has_retmsg();
  retmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Qot_RequestHistoryKLQuota.Response.retMsg)
}
inline ::std::string* Response::mutable_retmsg() {
  set_has_retmsg();
  // @@protoc_insertion_point(field_mutable:Qot_RequestHistoryKLQuota.Response.retMsg)
  return retmsg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Response::release_retmsg() {
  // @@protoc_insertion_point(field_release:Qot_RequestHistoryKLQuota.Response.retMsg)
  clear_has_retmsg();
  return retmsg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Response::set_allocated_retmsg(::std::string* retmsg) {
  if (retmsg != NULL) {
    set_has_retmsg();
  } else {
    clear_has_retmsg();
  }
  retmsg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), retmsg);
  // @@protoc_insertion_point(field_set_allocated:Qot_RequestHistoryKLQuota.Response.retMsg)
}

// optional int32 errCode = 3;
inline bool Response::has_errcode() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Response::set_has_errcode() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Response::clear_has_errcode() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Response::clear_errcode() {
  errcode_ = 0;
  clear_has_errcode();
}
inline ::google::protobuf::int32 Response::errcode() const {
  // @@protoc_insertion_point(field_get:Qot_RequestHistoryKLQuota.Response.errCode)
  return errcode_;
}
inline void Response::set_errcode(::google::protobuf::int32 value) {
  set_has_errcode();
  errcode_ = value;
  // @@protoc_insertion_point(field_set:Qot_RequestHistoryKLQuota.Response.errCode)
}

// optional .Qot_RequestHistoryKLQuota.S2C s2c = 4;
inline bool Response::has_s2c() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Response::set_has_s2c() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Response::clear_has_s2c() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Response::clear_s2c() {
  if (s2c_ != NULL) s2c_->Clear();
  clear_has_s2c();
}
inline const ::Qot_RequestHistoryKLQuota::S2C& Response::s2c() const {
  const ::Qot_RequestHistoryKLQuota::S2C* p = s2c_;
  // @@protoc_insertion_point(field_get:Qot_RequestHistoryKLQuota.Response.s2c)
  return p != NULL ? *p : *reinterpret_cast<const ::Qot_RequestHistoryKLQuota::S2C*>(
      &::Qot_RequestHistoryKLQuota::_S2C_default_instance_);
}
inline ::Qot_RequestHistoryKLQuota::S2C* Response::release_s2c() {
  // @@protoc_insertion_point(field_release:Qot_RequestHistoryKLQuota.Response.s2c)
  clear_has_s2c();
  ::Qot_RequestHistoryKLQuota::S2C* temp = s2c_;
  s2c_ = NULL;
  return temp;
}
inline ::Qot_RequestHistoryKLQuota::S2C* Response::mutable_s2c() {
  set_has_s2c();
  if (s2c_ == NULL) {
    s2c_ = new ::Qot_RequestHistoryKLQuota::S2C;
  }
  // @@protoc_insertion_point(field_mutable:Qot_RequestHistoryKLQuota.Response.s2c)
  return s2c_;
}
inline void Response::set_allocated_s2c(::Qot_RequestHistoryKLQuota::S2C* s2c) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete s2c_;
  }
  if (s2c) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      s2c = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, s2c, submessage_arena);
    }
    set_has_s2c();
  } else {
    clear_has_s2c();
  }
  s2c_ = s2c;
  // @@protoc_insertion_point(field_set_allocated:Qot_RequestHistoryKLQuota.Response.s2c)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Qot_RequestHistoryKLQuota

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Qot_5fRequestHistoryKLQuota_2eproto__INCLUDED
