// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Trd_UnlockTrade.proto

/*
Package Trd_UnlockTrade is a generated protocol buffer package.

It is generated from these files:
	Trd_UnlockTrade.proto

It has these top-level messages:
	C2S
	S2C
	Request
	Response
*/
package Trd_UnlockTrade

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/stephenlyu/gofutuapi/futuproto/Common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type C2S struct {
	Unlock           *bool   `protobuf:"varint,1,req,name=unlock" json:"unlock,omitempty"`
	PwdMD5           *string `protobuf:"bytes,2,opt,name=pwdMD5" json:"pwdMD5,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2S) Reset()                    { *m = C2S{} }
func (m *C2S) String() string            { return proto.CompactTextString(m) }
func (*C2S) ProtoMessage()               {}
func (*C2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *C2S) GetUnlock() bool {
	if m != nil && m.Unlock != nil {
		return *m.Unlock
	}
	return false
}

func (m *C2S) GetPwdMD5() string {
	if m != nil && m.PwdMD5 != nil {
		return *m.PwdMD5
	}
	return ""
}

type S2C struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2C) Reset()                    { *m = S2C{} }
func (m *S2C) String() string            { return proto.CompactTextString(m) }
func (*S2C) ProtoMessage()               {}
func (*S2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Request struct {
	C2S              *C2S   `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Request) GetC2S() *C2S {
	if m != nil {
		return m.C2S
	}
	return nil
}

type Response struct {
	// 以下3个字段每条协议都有，注释说明在InitConnect.proto中
	RetType          *int32  `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg           *string `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode          *int32  `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C              *S2C    `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

const Default_Response_RetType int32 = -400

func (m *Response) GetRetType() int32 {
	if m != nil && m.RetType != nil {
		return *m.RetType
	}
	return Default_Response_RetType
}

func (m *Response) GetRetMsg() string {
	if m != nil && m.RetMsg != nil {
		return *m.RetMsg
	}
	return ""
}

func (m *Response) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *Response) GetS2C() *S2C {
	if m != nil {
		return m.S2C
	}
	return nil
}

func init() {
	proto.RegisterType((*C2S)(nil), "Trd_UnlockTrade.C2S")
	proto.RegisterType((*S2C)(nil), "Trd_UnlockTrade.S2C")
	proto.RegisterType((*Request)(nil), "Trd_UnlockTrade.Request")
	proto.RegisterType((*Response)(nil), "Trd_UnlockTrade.Response")
}

func init() { proto.RegisterFile("Trd_UnlockTrade.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xe9, 0xba, 0xb9, 0x19, 0x05, 0xa1, 0xfe, 0xa0, 0x78, 0x90, 0xd2, 0x83, 0xec, 0x62,
	0x3a, 0x83, 0x3b, 0xe8, 0xd1, 0x78, 0x1d, 0x48, 0x5a, 0x2f, 0x5e, 0xa4, 0x6b, 0x9f, 0x5d, 0x71,
	0xed, 0x8b, 0xf9, 0x81, 0xec, 0xee, 0x1f, 0x2e, 0xe9, 0xd6, 0x4b, 0xf1, 0x14, 0x3e, 0xdf, 0x7c,
	0x5e, 0xde, 0x97, 0x90, 0xcb, 0x4c, 0x95, 0x1f, 0x6f, 0xed, 0x16, 0x8b, 0xaf, 0x4c, 0xe5, 0x25,
	0x50, 0xa9, 0xd0, 0x60, 0x70, 0x36, 0x88, 0xaf, 0x4f, 0x39, 0x36, 0x0d, 0xb6, 0xfb, 0xeb, 0x78,
	0x49, 0x7c, 0xce, 0xd2, 0xe0, 0x8a, 0x1c, 0xd9, 0xce, 0x09, 0xbd, 0x68, 0x34, 0x9f, 0x89, 0x03,
	0xb9, 0x5c, 0xfe, 0x94, 0xab, 0x97, 0x65, 0x38, 0x8a, 0xbc, 0xf9, 0xb1, 0x38, 0x50, 0x3c, 0x21,
	0x7e, 0xca, 0x78, 0x7c, 0x4f, 0xa6, 0x02, 0xbe, 0x2d, 0x68, 0x13, 0xdc, 0x12, 0xbf, 0x60, 0xba,
	0x1b, 0x3f, 0x61, 0x17, 0x74, 0x58, 0x86, 0xb3, 0x54, 0x38, 0x21, 0xfe, 0xf5, 0xc8, 0x4c, 0x80,
	0x96, 0xd8, 0x6a, 0x08, 0x6e, 0xc8, 0x54, 0x81, 0xc9, 0x76, 0x12, 0xba, 0xc1, 0xc9, 0xd3, 0xf8,
	0xee, 0x61, 0xb1, 0x10, 0x7d, 0xe8, 0xd6, 0x2b, 0x30, 0x2b, 0x5d, 0xf5, 0xeb, 0xf7, 0x14, 0x84,
	0x64, 0x0a, 0x4a, 0x71, 0x2c, 0x21, 0xf4, 0x23, 0x6f, 0x3e, 0x11, 0x3d, 0xba, 0x1a, 0x9a, 0x15,
	0xe1, 0x38, 0xf2, 0xfe, 0xad, 0x91, 0x32, 0x2e, 0x9c, 0xf0, 0xfc, 0x4a, 0xce, 0x0b, 0x6c, 0xe8,
	0xa7, 0x35, 0x96, 0xa2, 0x84, 0x36, 0x97, 0x35, 0x95, 0xeb, 0xf7, 0xc7, 0xaa, 0x36, 0x1b, 0xbb,
	0xa6, 0x05, 0x36, 0x89, 0x36, 0x20, 0x37, 0xd0, 0x6e, 0x77, 0x36, 0xa9, 0xd0, 0x89, 0xb9, 0xac,
	0x13, 0x77, 0x76, 0x3f, 0x97, 0x0c, 0x9e, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x47, 0x90, 0xe6,
	0xc3, 0x80, 0x01, 0x00, 0x00,
}
